apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
  labels: 
    app: tomcat
spec:
  containers:
    - name: test-container
      image: kku9/was-main:v9
      volumeMounts:
      - name: config-volume
        mountPath: /usr/local/tomcat/webapps/ROOT
      ports: 
      - containerPort: 8080
      securityContext: 
        readOnlyRootFilesystem: false
  volumes:
    - name: config-volume
      configMap:
        name: tomcat-cm
