apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhomegym-product-web
  labels:
    app: myhomegym-product
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myhomegym-product
  template:
    metadata:
      labels:
        app: myhomegym-product
    spec:
      containers:
      - image: ysryu/nginx-product:v1.0
        name: web-product
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "250m"
            memory: "250Mi"
          limits:
            memory: "250Mi"
            cpu: "250m"

---
apiVersion: v1
kind: Service
metadata:
  name: svc-product-web
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30300
  selector:
    app: myhomegym-product