apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpe-login
spec:
  maxReplicas: 10
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myhomegym-login-web
  targetCPUUtilizationPercentage: 60